title: [Project Name]
remote_theme: just-the-docs/just-the-docs
mermaid:
  version: "10.5.0" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title: ğŸ¤ Tip
    color: purple
  info:
    title: â„¹ï¸ Info
    color: blue
  attention:
    title: â• Attention
    color: yellow
  download:
    title: ğŸ’¾ Download
    color: grey-dk